peanutSeo:
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    title:
      type: string(255)
    description:
      type: string(255)
    keywords:
      type: string(195)
    is_indexable:
      default: true
      type: integer
      notnull: true
    is_followable:
      default: true
      type: integer
      notnull: true
